default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: arbuzzz
  username: postgres

development:
  <<: *default
  database: SampleApp_dev

test:
  <<: *default
  database: SampleApp_test

staging:
  <<: *default
  database: SampleApp

production:
  <<: *default
  database: SampleApp
